### ISSUE TITLE
přidat info o dostupnosti oai provideru

### ISSUE THREAD

**Issue by rzeh4n** [moravianlibrary/registr-krameriu#11]
Nepodařilo se mi najít jediný instalovaný a funkční oai provider. Je to volitelná komponenta, evidentně se moc nepoužívá, ale možná do budoucna bude mít smysl to sledovat. 
Mělo by stačit kontrolovat dostupnost url následujícího tvaru:
http://kramerius.mzk.cz/oaiprovider/?verb=Identify

**Comment by MartinRumanek** [comment]
Jenom doplním, že nyní je nová komponenta OAI, která běží nad SOLR. viz https://github.com/ceskaexpedice/kramerius/tree/master/installation/oai

která má potom jinou adresu solr_server/solr/oai, ale nevím jestli to mají někde nasazené

**Comment by honza-rychtar** [comment]
Hotovo.
