### ISSUE TITLE
Aktualizace registru

### ISSUE THREAD

**Issue by filak** [moravianlibrary/registr-krameriu#15]
Aktualizuje se prosím obsah registru? Vypadá to, že spíše ne (Posledni obnova 2016-04-24 16:33:54 UTC)

**Comment by honza-rychtar** [comment]
Aktualizoval se automaticky v noci ze vcerejska na dnesek (Posledni obnova 2016-08-28 22:00:25 UTC)
Ted jsem ho aktualizoval rucne.

**Comment by filak** [comment]
OK. Koukal jsem sem: https://registr-krameriu.herokuapp.com/

**Comment by honza-rychtar** [comment]
Aha, ten uz zrusim uplne.
Ted je aktualni na http://registrkrameriu.mzk.cz/ a http://registr.digitalniknihovna.cz/
Pozdeji zustane uz jen jeden - http://registrkrameriu.mzk.cz/
