### ISSUE TITLE
informace o krameriu svkul

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/registr-krameriu#17]
Proč nejsou v registru běžícím v MZK informace od svkul a v registru na digitalniknihovna jsou? Aktualizované jsou oba a Kramerius svkul beží.

**Comment by honza-rychtar** [comment]
Protoze presli na https a je problem s presmerovanim.
Na registr.digitalniknihovna.cz jsem u nich zmenil url. Na http://registrkrameriu.mzk.cz/ si nemuzu vzpomenout na heslo, takze to nemuzu editovat a na server jeste nemam pristup.
Rychly fix je pod adminem SVKUL -> detail -> upravt -> url (http zmenit na https)

Jinak bych mel asi poresit to presmerovani - i kdyz ono je to takto mozna lepsi, v registru by melo byt koncove url.

**Comment by zabak** [comment]
ok opraveno
