### ISSUE TITLE
Přidat linkování na nového web klienta

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/registr-krameriu#19]

**Comment by zabak** [comment]
Odstranit sloupec s novým klientem K5 a místo toho dát odkaz na web client. Asi bude muset být zadáváno přes formulář, protože každý si to může dát na libovolné URL. Konkrétně NK má kramerius na http://kramerius4.nkp.cz, v registru je ještě link na nového klienta na http://kramerius4.nkp.cz/client/, což ale nefunguje a nejde to odstranit ani změnit a nový klient jim běží na http://kramerius5.nkp.cz

**Comment by honza-rychtar** [comment]
Hotovo
