### ISSUE TITLE
Anglický překlad

### ISSUE THREAD

**Issue by BrozekAles** [moravianlibrary/registr-krameriu#20]
Vzhledem k tomu, že se na Registr Krameriů odkazuje ze zahraničí: http://anno.onb.ac.at/weitere_digipro.htm
bylo by vhodné mít i anglickou verzi, kde by byly přeloženy do angličtiny "hlavičky" jako název, verze, klienti, uživatelské rozhraní... A nepochopil jsem údaje ve sloupci Poslední přírůstek: 07.06.2019 39:39 1   Datum je zřejmé, ale 39:39 a 1 nechápu. Díky za vysvětlení.

**Comment by honza-rychtar** [comment]
> A nepochopil jsem údaje ve sloupci Poslední přírůstek: 07.06.2019 39:39 1 Datum je zřejmé, ale 39:39 a 1 nechápu. Díky za vysvětlení.

**39:39** byla chyba ve formátování času. Opravil jsem to.
**1** je počet dnů od posledního přírustku.

**Comment by BrozekAles** [comment]
Jojo, ten počet dnů od posledního přírůstku je zajímavý ukazatel, ale zatím nikoho z těch, kterým jsem to ukazoval, nenapadlo, že to je počet dnů. A přitom to nebyli žádní blbci :-)  Vyplatilo by se udělat nápovědu...

**Comment by zabak** [comment]
Anglický překlad přidán, zavírám
