### ISSUE TITLE
Diagnostika

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/registr-krameriu#5]
Moznost pustit diagnostiku (soubor testu) pro vybraneho Krameria.
Napr.
- Obsahuje Kramerius vybrane verejne dokumenty?
- Ma Kramerius nastaven vlastni info text?
- Najdi vsechna neverejna periodika, ktera obsahuji alespon jeden verejny rocnik
- Podezrela klicova slova (zretezeni vice klicovych slov)
- Spatny nazev (napr root_title je null)

V pripade nesplneni testu upozornit na problem, navrhnout reseni, vypsat chybne dokumenty - prokliky do Krameria, MODS apod.

**Comment by zabak** [comment]
Mělo by se stát součástí admin aplikace Krameria.

**Comment by honza-rychtar** [comment]
Bude součástí admin rozhraní Krameria.
